apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: freshfarm-eks
  region: us-east-1
  version: "1.36"

vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: freshfarm-workers

    instanceType: m7i-flex.large

    desiredCapacity: 1
    minSize: 1
    maxSize: 2

    volumeSize: 20

    privateNetworking: false

    labels:
      role: application

    tags:
      project: freshfarm
      environment: dev
